name: mast3r
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.9.1
  - asttokens=2.4.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.11.26
  - cairo=1.18.0
  - certifi=2024.12.14
  - charset-normalizer=2.0.4
  - cmake=3.14.0
  - comm=0.2.2
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.5.39
  - cuda-runtime=12.1.0
  - cuda-version=12.5
  - dav1d=1.2.1
  - debugpy=1.8.5
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.2
  - ffmpeg=7.0.1
  - filelock=3.13.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gnutls=3.7.9
  - graphite2=1.3.14
  - harfbuzz=8.5.0
  - icu=73.2
  - idna=3.7
  - importlib-metadata=8.4.0
  - importlib_metadata=8.4.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.27.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jpeg=9e
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libabseil=20240116.2
  - libass=0.17.1
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.10.1.7
  - libcurand=10.3.6.82
  - libcurl=8.7.1
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.4
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libglib=2.80.2
  - libgomp=14.1.0
  - libhwloc=2.11.2
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnghttp2=1.57.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopenvino=2024.1.0
  - libopenvino-auto-batch-plugin=2024.1.0
  - libopenvino-auto-plugin=2024.1.0
  - libopenvino-hetero-plugin=2024.1.0
  - libopenvino-intel-cpu-plugin=2024.1.0
  - libopenvino-intel-gpu-plugin=2024.1.0
  - libopenvino-intel-npu-plugin=2024.1.0
  - libopenvino-ir-frontend=2024.1.0
  - libopenvino-onnx-frontend=2024.1.0
  - libopenvino-paddle-frontend=2024.1.0
  - libopenvino-pytorch-frontend=2024.1.0
  - libopenvino-tensorflow-frontend=2024.1.0
  - libopenvino-tensorflow-lite-frontend=2024.1.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.21.0
  - libvpx=1.14.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxml2=2.13.5
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - networkx=3.3
  - numpy=1.26.4
  - numpy-base=1.26.4
  - ocl-icd=2.3.2
  - openh264=2.4.1
  - openjpeg=2.4.0
  - openssl=3.3.2
  - p11-kit=0.24.1
  - packaging=24.1
  - parso=0.8.4
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.0
  - pixman=0.44.2
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - psutil=6.0.0
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pure_eval=0.2.3
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.11.8
  - python_abi=3.11
  - pytorch=2.3.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - readline=8.2
  - requests=2.32.2
  - rhash=1.4.3
  - setuptools=69.5.1
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - stack_data=0.6.2
  - svt-av1=2.1.0
  - sympy=1.12
  - tbb=2021.13.0
  - tk=8.6.14
  - torchtriton=2.3.1
  - torchvision=0.15.2
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - urllib3=2.2.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.9
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.1
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - aiofiles==23.2.1
      - altair==5.3.0
      - annotated-types==0.7.0
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - bracex==2.4
      - build==1.2.1
      - cffi==1.17.1
      - clarabel==0.9.0
      - click==8.1.7
      - contourpy==1.2.1
      - cvxpy==1.5.2
      - cycler==0.12.1
      - cython==3.0.11
      - defusedxml==0.7.1
      - dnspython==2.6.1
      - ecos==2.0.14
      - einops==0.8.0
      - email-validator==2.2.0
      - faiss-cpu==1.9.0
      - fastapi==0.111.1
      - fastapi-cli==0.0.4
      - fastjsonschema==2.20.0
      - ffmpy==0.3.2
      - fonttools==4.53.1
      - fqdn==1.5.1
      - freetype-py==2.4.0
      - fsspec==2024.6.1
      - gradio==4.38.1
      - gradio-client==1.1.0
      - grpcio==1.64.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.23.5
      - imageio==2.34.2
      - importlib-resources==6.4.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kapture==1.1.10
      - kapture-localization==1.1.10
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - llvmlite==0.43.0
      - markdown==3.6
      - markdown-it-py==3.0.0
      - matplotlib==3.9.1
      - mdurl==0.1.2
      - mistune==3.0.2
      - natsort==8.4.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - notebook==7.2.2
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numpy-quaternion==2023.0.4
      - opencv-python==4.10.0.84
      - orjson==3.10.6
      - osqp==0.6.7.post0
      - overrides==7.7.0
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - piexif==1.1.3
      - pillow-heif==0.17.0
      - poselib==2.0.2
      - prometheus-client==0.20.0
      - protobuf==4.25.3
      - pycocotools==2.0.8
      - pycolmap==0.6.1
      - pycparser==2.22
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pydub==0.25.1
      - pyglet==1.5.29
      - pyopengl==3.1.0
      - pyparsing==3.1.2
      - pyproject-hooks==1.1.0
      - pyrender==0.1.45
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-json-logger==2.0.7
      - python-multipart==0.0.9
      - pytz==2024.1
      - qdldl==0.1.7.post4
      - referencing==0.35.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - roma==1.5.0
      - rpds-py==0.19.0
      - ruff==0.5.2
      - safetensors==0.4.3
      - scikit-image==0.25.0
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - scs==3.2.6
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - shellingham==1.5.4
      - sniffio==1.3.1
      - soupsieve==2.6
      - starlette==0.37.2
      - tabulate==0.9.0
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tifffile==2024.12.12
      - tinycss2==1.3.0
      - tomlkit==0.12.0
      - toolz==0.12.1
      - torchinfo==1.8.0
      - tqdm==4.66.4
      - transforms3d==0.4.2
      - trimesh==4.4.3
      - typer==0.12.3
      - types-python-dateutil==2.9.0.20240906
      - tzdata==2024.1
      - uri-template==1.3.0
      - uvicorn==0.30.1
      - uvloop==0.19.0
      - watchfiles==0.22.0
      - wcmatch==8.5.2
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==11.0.3
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.13
      - yacs==0.1.8
